name: Release

on: 
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Check Tag
        id: check-tag
        run: |
          if [[ "${{ github.ref }}" =~ alpha|beta ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          fi
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          prerelease: ${{ steps.check-tag.outputs.prerelease }}
          generateReleaseNotes: true